name: Build & Test
'on':
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  schedule:
    - cron: 0 16 * * *
  workflow_dispatch:
jobs:
  typescript-build:
    name: Test - Typescript
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./typescript

    strategy:
      matrix:
        node-version:
          - 16.x
          - 18.x
          - 20.x
          - 22.x
          - 24.x
    steps:
      - uses: actions/checkout@v2
      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v4
        with:
          node-version: '${{ matrix.node-version }}'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  modelcontextprotocol-build:
    name: Test - Model Context Protocol 
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./modelcontextprotocol

    strategy:
      matrix:
        node-version:
          - 16.x
          - 18.x
          - 20.x
          - 22.x
          - 24.x
    steps:
      - uses: actions/checkout@v2
      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v4
        with:
          node-version: '${{ matrix.node-version }}'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
